# 1. Data Cleaning & Format

In [ ]:
import os

os.environ["HF_TOKEN"] = "SECRET"

In [2]:
from src.preprocess_parquet import load_parquet, preProcess
import pandas as pd

pd.set_option('display.width', 1000) 

if False:
    DROP_TOPIC = [
        'An ninh quốc gia',
        'Cán bộ, công chức, viên chức',
        'Quốc phòng',
        'Chính sách xã hội',
        'Thống kê',
        'Xây dựng pháp luật và thi hành pháp luật',
        'Tổ chức bộ máy nhà nước',
        'Ngoại giao, điều ước quốc tế',
        'Dân số, gia đình, trẻ em, bình đẳng giới',
        'Hình sự',
        'Tổ chức chính trị - xã hội, hội',
        'Tương trợ tư pháp',
        'Dân tộc',
        'Tôn giáo, tín ngưỡng',
        'Văn thư lưu trữ'
    ]

    df = load_parquet("data/dataset.parquet")

    irrelevant_mask = df['topic_title'].isin(DROP_TOPIC)
    df = df[~irrelevant_mask]
    print(f"Drop {sum(irrelevant_mask)} samples theo chủ đề.")
    
    empty_mask = df['content_text'] == ""
    df = df[~empty_mask]
    print(f"Drop {sum(empty_mask)} samples có nội dung trống.")

    df = preProcess(df, save_path='data/processed_dataset.parquet',
                    fix_path = "data/error_correction.csv")

    print(f"Còn lại tổng cộng {len(df)} samples.")
    df

# 2. Retrieving

In [3]:
from src.preprocess_parquet import load
import pandas as pd

pd.set_option('display.width', 1000) 

df = load('data/processed_dataset.parquet')
df = df.drop(columns=['article_title', 'source_note_text', 'source_links', 'topic_title'])
df.head(1)

        docs_code            docs_title article_index  subject_title                                       content_text  content_word_count  content_clause_count
947  25/2008/QH12  Luật số 25/2008/QH12        Điều 1  Bảo hiểm y tế  {'title': '', 'content': [{'text': '1. Luật nà...                 135                     3

In [4]:
from src.recall_retriever import BM25
from src.data_presentation import Corpus, HierarchicalCorpus

corpus_simple = Corpus()
corpus_hier = HierarchicalCorpus(
    alpha = 0.5,
    title_blending = True
)

bm25_raw = BM25(
    name="BM25_ra",
    corpus= corpus_simple,
    top_k=10,
    norm=0.75
)
bm25_hier = BM25(
    name="BM25_hi",
    corpus= corpus_hier,
    top_k=10,
    norm=0.25
)

In [9]:
from sentence_transformers import SentenceTransformer
from src.recall_retriever import Dense

dense_model = SentenceTransformer(
    "intfloat/multilingual-e5-small",
    token=os.environ["HF_TOKEN"]
)

print(f"[INFO] Đã nạp xong dense model lên device={dense_model.device}.")

dense_raw = Dense(
    corpus_simple, dense_model,
    batch_size=32,
    top_k = 100, 
    M=32, ef_construction=512, ef_search=128,
    index_type='HNSW', name='DENSE_ra' 
)

dense_raw_flat = Dense(
    corpus_simple, dense_model,
    batch_size=32,
    top_k = 100, 
    index_type='Flat', name='DENSE_fl' 
)

dense_hier = Dense(
    corpus_hier, dense_model,
    batch_size=256,
    top_k = 2000, 
    M=256, ef_construction=4096, ef_search=2048,
    index_type='HNSW', name='DENSE_ra' 
)

dense_hier_flat = Dense(
    corpus_hier, dense_model,
    batch_size=256,
    top_k = 2000, 
    index_type='Flat', name='DENSE_fl' 
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[INFO] Đã nạp xong dense model lên device=cuda:0.

In [10]:
from src.retrieval_pipeline import RetrievalPipeline


retriever = RetrievalPipeline(
    data = df['content_text'],
    retrievalLayers=[dense_raw_flat, dense_hier]
)

[INFO] Đang build Corpuses
[INFO] [1/2] Đang build <class 'src.data_presentation.HierarchicalCorpus'>
[INFO] [2/2] Đang build <class 'src.data_presentation.Corpus'>
[INFO] Đang fit lớp Recall Retrievers
[INFO] [1/2] Đang fit <class 'src.recall_retriever.Dense'> với Knowledge Base <class 'src.data_presentation.Corpus'>

Batches:   0%|          | 0/1303 [00:00<?, ?it/s]

[INFO] [2/2] Đang fit <class 'src.recall_retriever.Dense'> với Knowledge Base <class 'src.data_presentation.HierarchicalCorpus'>

Batches:   0%|          | 0/999 [00:00<?, ?it/s]

# 3. Manual Evaluation

In [15]:
score = retriever.retrieve("Các cơ sở ươm tạo và khu làm việc chung được hưởng những chính sách hỗ trợ nào về thuế và đất đai")

score_board = pd.concat([df[['docs_code', 'article_index']], score], axis=1)

/mnt/082E39432E392AD8/Development Site/Code MESS/VS Code/Python/AI Guru/src/data_presentation.py:216: RuntimeWarning: divide by zero encountered in scalar divide
  mean = np.mean([self.min_penalty / penalty] * penalty + [item[1] for item in score_board])

In [16]:
score_board.sort_values(by="DENSE_ra_score", ascending=False).head(16)

              docs_code article_index  DENSE_fl_score  DENSE_ra_score DENSE_ra_comment
8898       04/2017/QH14       Điều 12        0.909680        0.919551           [3, 2]
17046      21/2008/QH12       Điều 22        0.908775        0.901958           [1, 1]
8901   07/2020/TT-BKHCN        Điều 4        0.870648        0.890830              [1]
17135     10/2024/NĐ-CP       Điều 12        0.895204        0.889607              [2]
17197     74/2017/NĐ-CP       Điều 12        0.887076        0.888162           [2, 1]
3271     154/2013/NĐ-CP       Điều 21        0.870353        0.887534             [12]
24219     57/2018/NĐ-CP        Điều 7        0.880391        0.886972              [3]
24179     57/2018/NĐ-CP        Điều 2        0.880877        0.885856              [2]
24112     77/2018/NĐ-CP        Điều 4        0.884264        0.885854           [1, 1]
17196     74/2017/NĐ-CP       Điều 11        0.881897        0.885395              [3]
24161     40/2017/NĐ-CP       Điều 15        0.885173        0.885172               []
3272     154/2013/NĐ-CP       Điều 22        0.878460        0.883496              [1]
9223       17/2023/QH15       Điều 28        0.879742        0.883247           [1, 3]
33320             84-CP       Điều 10        0.883210        0.883210               []
17137     10/2024/NĐ-CP       Điều 14             NaN        0.882071              [4]
23443    38/2016/QĐ-TTG        Điều 7        0.871946        0.882009              [3]

In [17]:
score_board.sort_values(by="DENSE_fl_score", ascending=False).head(16)

                 docs_code article_index  DENSE_fl_score  DENSE_ra_score DENSE_ra_comment
8898          04/2017/QH14       Điều 12        0.909680        0.919551           [3, 2]
17046         21/2008/QH12       Điều 22        0.908775        0.901958           [1, 1]
17135        10/2024/NĐ-CP       Điều 12        0.895204        0.889607              [2]
17138        10/2024/NĐ-CP       Điều 15        0.892688        0.778501              [5]
8902      07/2020/TT-BKHCN        Điều 5        0.888460        0.880955           [1, 2]
17197        74/2017/NĐ-CP       Điều 12        0.887076        0.888162           [2, 1]
17199        74/2017/NĐ-CP       Điều 14        0.886274        0.877408              [1]
24161        40/2017/NĐ-CP       Điều 15        0.885173        0.885172               []
33344      153/2011/TT-BTC        Điều 1        0.884816        0.731894              [2]
33372         48/2010/QH12        Điều 9        0.884672        0.729480              [7]
24112        77/2018/NĐ-CP        Điều 4        0.884264        0.885854           [1, 1]
2389          49/2010/QH12       Điều 34        0.883780        0.880146           [3, 1]
33320                84-CP       Điều 10        0.883210        0.883210               []
8691      07/2020/TT-BKHCN        Điều 2        0.882644        0.878240              [2]
17122         21/2008/QH12       Điều 28        0.882347        0.792119           [2, 1]
23588  15/2001/TT-BNN-PCLB        Điều 3        0.881968        0.881968               []

In [18]:
df.loc[18195]['content_text']

{'title': 'Người lao động làm thêm giờ vào ban đêm theo khoản 3 Điều 98 của Bộ luật Lao động, được hưởng tiền lương tính theo công thức sau:',
 'content': [{'title': '1. Đối với người lao động hưởng lương theo thời gian, tiền lương làm thêm giờ vào ban đêm được tính như sau: Trong đó:',
   'content': [{'text': 'a) Tiền lương giờ thực trả của công việc đang làm vào ngày làm việc bình thường được xác định theo điểm a khoản 1 Điều 55 Nghị định này;'},
    {'text': 'b) Tiền lương giờ vào ban ngày của ngày làm việc bình thường hoặc của ngày nghỉ hằng tuần hoặc của ngày nghỉ lễ, tết, ngày nghỉ có hưởng lương được xác định như sau: b1) Tiền lương giờ vào ban ngày của ngày làm việc bình thường, được tính ít nhất bằng 100% so với tiền lương giờ thực trả của công việc đang làm vào ngày làm việc bình thường đối với trường hợp người lao động không làm thêm giờ vào ban ngày của ngày đó (trước khi làm thêm giờ vào ban đêm); ít nhất bằng 150% so với tiền lương giờ thực trả của công việc đang làm vào ngày làm việc bình thường đối với trường hợp người lao động có làm thêm giờ vào ban ngày của ngày đó (trước khi làm thêm giờ vào ban đêm); b2) Tiền lương giờ vào ban ngày của ngày nghỉ hằng tuần, được tính ít nhất bằng 200% so với tiền lương giờ thực trả của công việc đang làm vào ngày làm việc bình thường; b3) Tiền lương giờ vào ban ngày của ngày nghỉ lễ, tết, ngày nghỉ có hưởng lương, được tính ít nhất bằng 300% so với tiền lương giờ thực trả của công việc đang làm vào ngày làm việc bình thường.'}]},
  {'title': '2. Đối với người lao động hưởng lương theo sản phẩm, tiền lương làm thêm giờ vào ban đêm được tính như sau: Trong đó, đơn giá tiền lương sản phẩm vào ban ngày của ngày làm việc bình thường hoặc của ngày nghỉ hằng tuần hoặc của ngày nghỉ lễ, tết, ngày nghỉ có hưởng lương được xác định như sau:',
   'content': [{'text': 'a) Đơn giá tiền lương sản phẩm vào ban ngày của ngày làm việc bình thường, được tính ít nhất bằng 100% so với đơn giá tiền lương sản phẩm của ngày làm việc bình thường đối với trường hợp người lao động không làm thêm giờ vào ban ngày của ngày đó (trước khi làm thêm giờ vào ban đêm); ít nhất bằng 150% so với đơn giá tiền lương sản phẩm của ngày làm việc bình thường đối với trường hợp người lao động có làm thêm giờ vào ban ngày của ngày đó (trước khi làm thêm giờ vào ban đêm);'},
    {'text': 'b) Đơn giá tiền lương sản phẩm vào ban ngày của ngày nghỉ hằng tuần, được tính ít nhất bằng 200% so với đơn giá tiền lương sản phẩm của ngày làm việc bình thường;'},
    {'text': 'c) Đơn giá tiền lương sản phẩm vào ban ngày của ngày nghỉ lễ, tết, ngày nghỉ có hưởng lương, được tính ít nhất 300% so với đơn giá tiền lương sản phẩm của ngày làm việc bình thường. (Điều này có nội dung liên quan đến Điều 20.2.LQ.98. Tiền lương làm thêm giờ, làm việc vào ban đêm ; Điều 20.2.NĐ.3.55. Tiền lương làm thêm giờ ) Điều 20.2.LQ.99. Tiền lương ngừng việc (Điều 99 Bộ luật số 45/2019/QH14, có hiệu lực thi hành kể từ ngày 01/01/2021) Trường hợp phải ngừng việc, người lao động được trả lương như sau: 1. Nếu do lỗi của người sử dụng lao động thì người lao động được trả đủ tiền lương theo hợp đồng lao động; 2. Nếu do lỗi của người lao động thì người đó không được trả lương; những người lao động khác trong cùng đơn vị phải ngừng việc thì được trả lương theo mức do hai bên thỏa thuận nhưng không được thấp hơn mức lương tối thiểu;'}]},
  {'title': '3. Nếu vì sự cố về điện, nước mà không do lỗi của người sử dụng lao động hoặc do thiên tai, hỏa hoạn, dịch bệnh nguy hiểm, địch họa, di dời địa điểm hoạt động theo yêu cầu của cơ quan nhà nước có thẩm quyền hoặc vì lý do kinh tế thì hai bên thỏa thuận về tiền lương ngừng việc như sau:',
   'content': [{'text': 'a) Trường hợp ngừng việc từ 14 ngày làm việc trở xuống thì tiền lương ngừng việc được thỏa thuận không thấp hơn mức lương tối thiểu;'},
    {'text': 'b) Trường hợp phải ngừng việc trên 14 ngày làm việc thì tiền lương ngừng việc do hai bên thỏa thuận nhưng phải bảo đảm tiền lương ngừng việc trong 14 ngày đầu tiên không thấp hơn mức lương tối thiểu. (Điều này có nội dung liên quan đến Điều 20.2.LQ.29. Chuyển người lao động làm công việc khác so với hợp đồng lao động ; Điều 20.2.LQ.207. Tiền lương và các quyền lợi hợp pháp khác của người lao động trong thời gian đình công ) Điều 20.2.LQ.100. Trả lương thông qua người cai thầu (Điều 100 Bộ luật số 45/2019/QH14, có hiệu lực thi hành kể từ ngày 01/01/2021) 1. Nơi nào sử dụng người cai thầu hoặc người có vai trò trung gian tương tự thì người sử dụng lao động là chủ chính phải có danh sách và địa chỉ của những người này kèm theo danh sách những người lao động làm việc với họ và phải bảo đảm việc họ tuân thủ quy định của pháp luật về trả lương, an toàn, vệ sinh lao động. 2. Trường hợp người cai thầu hoặc người có vai trò trung gian tương tự không trả lương hoặc trả lương không đầy đủ và không bảo đảm các quyền lợi khác cho người lao động thì người sử dụng lao động là chủ chính phải chịu trách nhiệm trả lương và bảo đảm các quyền lợi cho người lao động. Trong trường hợp này, người sử dụng lao động là chủ chính có quyền yêu cầu người cai thầu hoặc người có vai trò trung gian tương tự đền bù hoặc yêu cầu cơ quan nhà nước có thẩm quyền giải quyết tranh chấp theo quy định của pháp luật. Điều 20.2.LQ.101. Tạm ứng tiền lương (Điều 101 Bộ luật số 45/2019/QH14, có hiệu lực thi hành kể từ ngày 01/01/2021) 1. Người lao động được tạm ứng tiền lương theo điều kiện do hai bên thỏa thuận và không bị tính lãi. 2. Người sử dụng lao động phải cho người lao động tạm ứng tiền lương tương ứng với số ngày người lao động tạm thời nghỉ việc để thực hiện nghĩa vụ công dân từ 01 tuần trở lên nhưng tối đa không quá 01 tháng tiền lương theo hợp đồng lao động và người lao động phải hoàn trả số tiền đã tạm ứng. Người lao động nhập ngũ theo quy định của Luật Nghĩa vụ quân sự thì không được tạm ứng tiền lương. 3. Khi nghỉ hằng năm, người lao động được tạm ứng một khoản tiền ít nhất bằng tiền lương của những ngày nghỉ. (Điều này có nội dung liên quan đến Điều 20.2.LQ.113. Nghỉ hằng năm ) Điều 20.2.LQ.102. Khấu trừ tiền lương (Điều 102 Bộ luật số 45/2019/QH14, có hiệu lực thi hành kể từ ngày 01/01/2021) 1. Người sử dụng lao động chỉ được khấu trừ tiền lương của người lao động để bồi thường thiệt hại do làm hư hỏng dụng cụ, thiết bị, tài sản của người sử dụng lao động theo quy định tại Điều 129 của Bộ luật này. 2. Người lao động có quyền được biết lý do khấu trừ tiền lương của mình. 3. Mức khấu trừ tiền lương hằng tháng không được quá 30% tiền lương thực trả hằng tháng của người lao động sau khi trích nộp các khoản bảo hiểm xã hội bắt buộc, bảo hiểm y tế, bảo hiểm thất nghiệp, thuế thu nhập cá nhân. (Điều này có nội dung liên quan đến Điều 20.2.LQ.129. Bồi thường thiệt hại ) Điều 20.2.LQ.103. Chế độ nâng lương, nâng bậc, phụ cấp, trợ cấp (Điều 103 Bộ luật số 45/2019/QH14, có hiệu lực thi hành kể từ ngày 01/01/2021) Chế độ nâng lương, nâng bậc, phụ cấp, trợ cấp và các chế độ khuyến khích đối với người lao động được thỏa thuận trong hợp đồng lao động, thỏa ước lao động tập thể hoặc quy định của người sử dụng lao động. Điều 20.2.LQ.104. Thưởng (Điều 104 Bộ luật số 45/2019/QH14, có hiệu lực thi hành kể từ ngày 01/01/2021) 1. Thưởng là số tiền hoặc tài sản hoặc bằng các hình thức khác mà người sử dụng lao động thưởng cho người lao động căn cứ vào kết quả sản xuất, kinh doanh, mức độ hoàn thành công việc của người lao động. 2. Quy chế thưởng do người sử dụng lao động quyết định và công bố công khai tại nơi làm việc sau khi tham khảo ý kiến của tổ chức đại diện người lao động tại cơ sở đối với nơi có tổ chức đại diện người lao động tại cơ sở. (Điều này có nội dung liên quan đến Điều 20.2.LQ.63. Tổ chức đối thoại tại nơi làm việc ; Điều 20.2.NĐ.3.41. Tổ chức đối thoại khi có vụ việc ; Điều 20.2.NĐ.3.55. Tiền lương làm thêm giờ ; Điều 20.2.TT.2.3. Nội dung chủ yếu của hợp đồng lao động ) Chương VII THỜI GIỜ LÀM VIỆC, THỜI GIỜ NGHỈ NGƠI (Chương này có nội dung liên quan đến Điều 20.2.NĐ.3.89. Một số quy định riêng đối với lao động là người giúp việc gia đình của Nghị định 145/2020/NĐ-CP Quy định chi tiết và hướng dẫn thi hành một số điều của Bộ luật Lao động về điều kiện lao động và quan hệ lao động ban hành ngày 14/12/2020 ) Mục 1 THỜI GIỜ LÀM VIỆC Điều 20.2.LQ.105. Thời giờ làm việc bình thường (Điều 105 Bộ luật số 45/2019/QH14, có hiệu lực thi hành kể từ ngày 01/01/2021) 1. Thời giờ làm việc bình thường không quá 08 giờ trong 01 ngày và không quá 48 giờ trong 01 tuần. 2. Người sử dụng lao động có quyền quy định thời giờ làm việc theo ngày hoặc tuần nhưng phải thông báo cho người lao động biết; trường hợp theo tuần thì thời giờ làm việc bình thường không quá 10 giờ trong 01 ngày và không quá 48 giờ trong 01 tuần. Nhà nước khuyến khích người sử dụng lao động thực hiện tuần làm việc 40 giờ đối với người lao động. 3. Người sử dụng lao động có trách nhiệm bảo đảm giới hạn thời gian làm việc tiếp xúc với yếu tố nguy hiểm, yếu tố có hại đúng theo quy chuẩn kỹ thuật quốc gia và pháp luật có liên quan. (Điều này có nội dung liên quan đến Điều 20.2.NĐ.3.54. Hình thức trả lương ; Điều 20.2.NĐ.3.55. Tiền lương làm thêm giờ ; Điều 20.2.TT.4.3. Quỹ thời giờ làm việc tiêu chuẩn trong năm ; Điều 41.11.TT.55.3. Nội dung định mức kinh tế - kỹ thuật ; Điều 41.11.TT.56.3. Nội dung định mức kinh tế - kỹ thuật ; Điều 41.5.TT.5.3. Nội dung, kết cấu định mức kinh tế - kỹ thuật ; Điều 41.11.TT.58.3. Nội dung định mức kinh tế - kỹ thuật ; Điều 41.11.TT.59.3. Nội dung định mức kinh tế - kỹ thuật ; Điều 41.5.TT.6.3. Nội dung, kết cấu định mức kinh tế - kỹ thuật ) Điều 20.2.NĐ.3.58. Thời giờ được tính vào thời giờ làm việc được hưởng lương (Điều 58 Nghị định số 145/2020/NĐ-CP, có hiệu lực thi hành kể từ ngày 01/02/2021) 1. Nghỉ giữa giờ quy định khoản 2 Điều 64 Nghị định này. 2. Nghỉ giải lao theo tính chất của công việc. 3. Nghỉ cần thiết trong quá trình lao động đã được tính trong định mức lao động cho nhu cầu sinh lý tự nhiên của con người.'}]},
  {'text': '4. Thời giờ nghỉ đối với lao động nữ khi mang thai hoặc nuôi con dưới 12 tháng tuổi, trong thời gian hành kinh theo quy định tại khoản 2 và khoản 4 Điều 137 của Bộ luật Lao động.'},
  {'text': '5. Thời giờ phải ngừng việc không do lỗi của người lao động.'},
  {'text': '6. Thời giờ hội họp, học tập, tập huấn do yêu cầu của người sử dụng lao động hoặc được người sử dụng lao động đồng ý.'},
  {'text': '7. Thời giờ người học nghề, tập nghề trực tiếp hoặc tham gia lao động theo quy định tại khoản 5 Điều 61 của Bộ luật Lao động.'},
  {'text': '8. Thời giờ mà người lao động là thành viên ban lãnh đạo của tổ chức đại diện người lao động tại cơ sở được sử dụng để thực hiện nhiệm vụ theo quy định tại khoản 2 và khoản 3 Điều 176 của Bộ luật Lao động.'},
  {'text': '9. Thời giờ khám sức khỏe, khám phát hiện bệnh nghề nghiệp, giám định y khoa để xác định mức độ suy giảm khả năng lao động do tai nạn lao động, bệnh nghề nghiệp, nếu thời giờ đó được thực hiện theo sự bố trí hoặc do yêu cầu của người sử dụng lao động.'},
  {'title': '10. Thời giờ đăng ký, khám, kiểm tra sức khỏe nghĩa vụ quân sự, nếu thời giờ đó được hưởng nguyên lương theo quy định của pháp luật về nghĩa vụ quân sự. (Điều này có nội dung liên quan đến Điều 20.2.LQ.61. Học nghề, tập nghề để làm việc cho người sử dụng lao động ; Điều 20.2.LQ.137. Bảo vệ thai sản ; Điều 20.2.LQ.176. Quyền của thành viên ban lãnh đạo của tổ chức đại diện người lao động tại cơ sở ; Điều 20.2.NĐ.3.60. Giới hạn số giờ làm thêm ; Điều 20.2.NĐ.3.64. Nghỉ trong giờ làm việc ) Điều 20.2.NĐ.3.63. Ca làm việc và tổ chức làm việc theo ca (Điều 63 Nghị định số 145/2020/NĐ-CP, có hiệu lực thi hành kể từ ngày 01/02/2021) 1. Ca làm việc là khoảng thời gian làm việc của người lao động từ khi bắt đầu nhận nhiệm vụ cho đến khi kết thúc và bàn giao nhiệm vụ cho người khác, bao gồm cả thời gian làm việc và thời gian nghỉ giữa giờ. 2. Tổ chức làm việc theo ca là việc bố trí ít nhất 02 người hoặc 02 nhóm người thay phiên nhau làm việc trên cùng một vị trí làm việc, tính trong thời gian 01 ngày (24 giờ liên tục). 3. Trường hợp làm việc theo ca liên tục để được tính nghỉ giữa giờ vào giờ làm việc quy định tại khoản 1 Điều 109 của Bộ luật Lao động là trường hợp tổ chức làm việc theo ca quy định tại khoản 2 Điều này khi ca làm việc đó có đủ các điều kiện sau:',
   'content': [{'text': 'a) Người lao động làm việc trong ca từ 06 giờ trở lên;'},
    {'text': 'b) Thời gian chuyển tiếp giữa hai ca làm việc liền kề không quá 45 phút. (Điều này có nội dung liên quan đến Điều 20.2.LQ.109. Nghỉ trong giờ làm việc ; Điều 20.2.NĐ.3.64. Nghỉ trong giờ làm việc ) Điều 20.2.NĐ.3.64. Nghỉ trong giờ làm việc (Điều 64 Nghị định số 145/2020/NĐ-CP, có hiệu lực thi hành kể từ ngày 01/02/2021) 1. Thời gian nghỉ giữa giờ ít nhất 45 phút liên tục theo quy định tại khoản 1 Điều 109 của Bộ luật Lao động được áp dụng đối với người lao động làm việc từ 06 giờ trở lên trong một ngày, trong đó có ít nhất 03 giờ làm việc trong khung giờ làm việc ban đêm quy định tại Điều 106 của Bộ luật Lao động. 2. Thời gian nghỉ giữa giờ được tính vào giờ làm việc đối với trường hợp làm việc theo ca liên tục quy định tại khoản 3 Điều 63 Nghị định này ít nhất 30 phút, riêng trường hợp làm việc ban đêm thì được tính ít nhất 45 phút. 3. Người sử dụng lao động quyết định thời điểm nghỉ trong giờ làm việc, nhưng không được bố trí thời gian nghỉ này vào thời điểm bắt đầu hoặc kết thúc ca làm việc. 4. Ngoài trường hợp làm việc theo ca liên tục quy định tại khoản 3 Điều 63 Nghị định này, khuyến khích các bên thương lượng thời gian nghỉ giữa giờ tính vào giờ làm việc. (Điều này có nội dung liên quan đến Điều 20.2.LQ.106. Giờ làm việc ban đêm ; Điều 20.2.LQ.109. Nghỉ trong giờ làm việc ; Điều 20.2.NĐ.3.58. Thời giờ được tính vào thời giờ làm việc được hưởng lương ; Điều 20.2.NĐ.3.63. Ca làm việc và tổ chức làm việc theo ca ) Điều 20.2.LQ.106. Giờ làm việc ban đêm (Điều 106 Bộ luật số 45/2019/QH14, có hiệu lực thi hành kể từ ngày 01/01/2021) Giờ làm việc ban đêm được tính từ 22 giờ đến 06 giờ sáng ngày hôm sau. (Điều này có nội dung liên quan đến Điều 20.2.NĐ.3.64. Nghỉ trong giờ làm việc ) Điều 20.2.LQ.107. Làm thêm giờ (Điều 107 Bộ luật số 45/2019/QH14, có hiệu lực thi hành kể từ ngày 01/01/2021) 1. Thời gian làm thêm giờ là khoảng thời gian làm việc ngoài thời giờ làm việc bình thường theo quy định của pháp luật, thỏa ước lao động tập thể hoặc nội quy lao động. 2. Người sử dụng lao động được sử dụng người lao động làm thêm giờ khi đáp ứng đầy đủ các yêu cầu sau đây:'},
    {'text': 'a) Phải được sự đồng ý của người lao động;'},
    {'text': 'b) Bảo đảm số giờ làm thêm của người lao động không quá 50% số giờ làm việc bình thường trong 01 ngày; trường hợp áp dụng quy định thời giờ làm việc bình thường theo tuần thì tổng số giờ làm việc bình thường và số giờ làm thêm không quá 12 giờ trong 01 ngày; không quá 40 giờ trong 01 tháng;'},
    {'text': 'c) Bảo đảm số giờ làm thêm của người lao động không quá 200 giờ trong 01 năm, trừ trường hợp quy định tại khoản 3 Điều này. 3. Người sử dụng lao động được sử dụng người lao động làm thêm không quá 300 giờ trong 01 năm trong một số ngành, nghề, công việc hoặc trường hợp sau đây:'},
    {'text': 'a) Sản xuất, gia công xuất khẩu sản phẩm hàng dệt, may, da, giày, điện, điện tử, chế biến nông, lâm, diêm nghiệp, thủy sản;'},
    {'text': 'b) Sản xuất, cung cấp điện, viễn thông, lọc dầu; cấp, thoát nước;'},
    {'text': 'c) Trường hợp giải quyết công việc đòi hỏi lao động có trình độ chuyên môn, kỹ thuật cao mà thị trường lao động không cung ứng đầy đủ, kịp thời;'},
    {'text': 'd) Trường hợp phải giải quyết công việc cấp bách, không thể trì hoãn do tính chất thời vụ, thời điểm của nguyên liệu, sản phẩm hoặc để giải quyết công việc phát sinh do yếu tố khách quan không dự liệu trước, do hậu quả thời tiết, thiên tai, hỏa hoạn, địch họa, thiếu điện, thiếu nguyên liệu, sự cố kỹ thuật của dây chuyền sản xuất; đ) Trường hợp khác do Chính phủ quy định. 4. Khi tổ chức làm thêm giờ theo quy định tại khoản 3 Điều này, người sử dụng lao động phải thông báo bằng văn bản cho cơ quan chuyên môn về lao động thuộc Ủy ban nhân dân cấp tỉnh. 5. Chính phủ quy định chi tiết Điều này. (Điều này có nội dung liên quan đến Điều 20.2.LQ.108. Làm thêm giờ trong trường hợp đặc biệt ; Điều 20.2.NĐ.3.1. Phạm vi điều chỉnh ; Điều 20.2.NĐ.3.60. Giới hạn số giờ làm thêm ; Điều 20.2.NĐ.3.61. Các trường hợp được tổ chức làm thêm từ trên 200 giờ đến 300 giờ trong một năm ) Điều 20.2.NĐ.3.59. Sự đồng ý của người lao động khi làm thêm giờ (Điều 59 Nghị định số 145/2020/NĐ-CP, có hiệu lực thi hành kể từ ngày 01/02/2021) 1. Trừ các trường hợp quy định tại Điều 108 của Bộ luật Lao động, các trường hợp khác khi tổ chức làm thêm giờ, người sử dụng lao động phải được sự đồng ý của người lao động tham gia làm thêm về các nội dung sau đây:'},
    {'text': 'a) Thời gian làm thêm;'},
    {'text': 'b) Địa điểm làm thêm;'},
    {'text': 'c) Công việc làm thêm. 2. Trường hợp sự đồng ý của người lao động được ký thành văn bản riêng thì tham khảo Mẫu số 01/PLIV Phụ lục IV ban hành kèm theo Nghị định này. (Điều này có nội dung liên quan đến Điều 20.2.LQ.108. Làm thêm giờ trong trường hợp đặc biệt ; Điều 20.2.TT.3.5. Làm thêm giờ ) Điều 20.2.NĐ.3.60. Giới hạn số giờ làm thêm (Điều 60 Nghị định số 145/2020/NĐ-CP, có hiệu lực thi hành kể từ ngày 01/02/2021) 1. Tổng số giờ làm thêm không quá 50% số giờ làm việc bình thường trong 01 ngày khi làm thêm vào ngày làm việc bình thường, trừ trường hợp quy định tại khoản 2, khoản 3 Điều này. 2. Trường hợp áp dụng quy định thời giờ làm việc bình thường theo tuần thì tổng số giờ làm việc bình thường và số giờ làm thêm không quá 12 giờ trong 01 ngày. 3. Trường hợp làm việc không trọn thời gian quy định tại Điều 32 của Bộ luật Lao động thì tổng số giờ làm việc bình thường và số giờ làm thêm không quá 12 giờ trong 01 ngày. 4. Tổng số giờ làm thêm không quá 12 giờ trong một ngày, khi làm thêm vào ngày nghỉ lễ, tết và ngày nghỉ hàng tuần. 5. Thời giờ quy định tại các khoản 1 Điều 58 Nghị định này được giảm trừ khi tính tổng số giờ làm thêm trong tháng, trong năm để xác định việc tuân thủ quy định tại điểm b, điểm c khoản 2 Điều 107 của Bộ luật Lao động. (Điều này có nội dung liên quan đến Điều 20.2.LQ.32. Làm việc không trọn thời gian ; Điều 20.2.LQ.107. Làm thêm giờ ; Điều 20.2.NĐ.3.58. Thời giờ được tính vào thời giờ làm việc được hưởng lương ) Điều 20.2.NĐ.3.61. Các trường hợp được tổ chức làm thêm từ trên 200 giờ đến 300 giờ trong một năm (Điều 61 Nghị định số 145/2020/NĐ-CP, có hiệu lực thi hành kể từ ngày 01/02/2021) Ngoài các trường hợp quy định tại các điểm a, điểm b, điểm c, điểm d khoản 3 Điều 107 của Bộ luật Lao động, các trường hợp sau đây được tổ chức làm thêm từ trên 200 giờ đến 300 giờ trong năm: 1. Các trường hợp phải giải quyết công việc cấp bách, không thể trì hoãn phát sinh từ các yếu tố khách quan liên quan trực tiếp đến hoạt động công vụ trong các cơ quan, đơn vị nhà nước, trừ các trường hợp quy định tại Điều 108 của Bộ luật Lao động. 2. Cung ứng dịch vụ công; dịch vụ khám bệnh, chữa bệnh; dịch vụ giáo dục, giáo dục nghề nghiệp. 3. Công việc trực tiếp sản xuất, kinh doanh tại các doanh nghiệp thực hiện thời giờ làm việc bình thường không quá 44 giờ trong một tuần. (Điều này có nội dung liên quan đến Điều 20.2.LQ.107. Làm thêm giờ ; Điều 20.2.LQ.108. Làm thêm giờ trong trường hợp đặc biệt ) Điều 20.2.NĐ.3.62. Thông báo về việc tổ chức làm thêm từ trên 200 giờ đến 300 giờ trong một năm (Điều 62 Nghị định số 145/2020/NĐ-CP, có hiệu lực thi hành kể từ ngày 01/02/2021) 1. Khi tổ chức làm thêm từ trên 200 giờ đến 300 giờ trong một năm, người sử dụng lao động phải thông báo cho Sở Lao động - Thương binh và Xã hội tại các nơi sau:'},
    {'text': 'a) Nơi người sử dụng lao động tổ chức làm thêm từ trên 200 giờ đến 300 giờ trong một năm;'},